### ISSUE TITLE
improve input data structure for updating project 

### ISSUE THREAD

**Issue by hurngchunlee** [Donders-Institute/filer-gateway#3]
The project resource can be updated by sending a `PATCH` request to the project endpoint, e.g. `/projects/<projectId>`.

However, the input data of the request requires both the `members` and `storage` to be provided, which is not necessary if only one of them to be updated.

## solution

None of the two attributes should be required.  If none of them being provided in the request data, the server takes no update action and returns `204 - No content` (?)

**Comment by hurngchunlee** [comment]
@Jascha-N I improved the API interface concerning the data for the PATCH operation.

Hereafter is an example data for project:

```json
{
  "members": [
    {
      "role": "manager",
      "userID": "string"
    }
  ],
  "storage": {
    "quotaGb": 0
  }
}
```

and example data for user (home quota):

```json
{
  "storage": {
    "quotaGb": 0
  }
}
```

- The `members` and `storage` are both optional now,
- If none of the attributes are provided, it returns `204 - no content`.
- If you only need to change the storage quota, just provide the `storage` attribute.  Within this attribute, only the `quotaGb` is mandatory, the `system` is no longer needed because the PATCH assumes that the project path has already been provisioned before on a given system, and that system can be determined from the project path on the server.
- If you only need to change the members, just provide the `members` attribute.  As I mentioned in our earlier discussion, you use `"role": "none"` to delete a member.

For more detail, see the API document [here for project](http://dccn-pl001.dccn.nl:8080/v1/docs#/default/patch_projects__id_) and [here for user](http://dccn-pl001.dccn.nl:8080/v1/docs#/default/patch_users__id_).

ps. the improvement is only deployed to the playground.  Let me know if you have any comment.

**Comment by hurngchunlee** [comment]
@Jascha-N I suppose this issue can be closed? do you agree?

**Comment by Jascha-N** [comment]
Yes, this can be closed
